name: Release utils package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci --prefix ./utils
      - run: npm test --prefix ./utils
      - run: npm run --prefix ./utils lint

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
      - run: npm ci --prefix ./utils
      - run: npm run --prefix ./utils package
      - run: npm publish ./utils/package
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
