name: Release svelte package

on:
  push:
    tags:
      - 'svelte*'

jobs:
  lint:
    uses: ./.github/workflows/lint.yml
  publish:
    needs: lint
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
      - run: npm ci --prefix ./svelte
      - run: npm run --prefix ./svelte lint
      - run: npm run --prefix ./svelte package
      - run: npm publish ./svelte/package
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
