name: Release utils package

on:
  push:
    tags:
      - 'utils*'

jobs:
  lint:
    uses: ./.github/workflows/lint.yml

  publish-gpr:
    needs: lint
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
      - run: npm ci --prefix ./utils
      - run: npm run --prefix ./utils package
      - run: npm publish ./utils/package
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
